/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.planning.view.AdminDept;

import com.planning.dao.implement.GroupeDAO;
import com.planning.dao.implement.MatiereDAO;
import com.planning.model.ConnexionBD;
import com.planning.model.Filiere;
import com.planning.model.Groupe;
import com.planning.model.Matiere;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Azough Mehdi
 */
public class AjouterMat extends javax.swing.JFrame {
       Connection conn = ConnexionBD.init();
       MatiereDAO matieredao;
       Matiere matiere;
       GererMatiere gererMatiere;
       int oldMat;
       
    public AjouterMat() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void setOldMat(int x){
        this.oldMat = x;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        matierefield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Sauvegarder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 114, 36));
        getContentPane().add(matierefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 200, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nom *");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        setSize(new java.awt.Dimension(389, 185));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       
       String nommat = matierefield.getText();
       if(!nommat.equals("")) {
            int p = JOptionPane.showConfirmDialog(null,"Etes-vous sur de vouloir sauvegarder?","Confirmation",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null);
            
            if(p == JOptionPane.YES_OPTION){
                matieredao = new MatiereDAO(conn);
                
                
                if(this.getTitle().equals("Modifier la matiere")) {
                    matieredao.update(new Matiere(this.oldMat, nommat));
                } else {
                    matieredao.create(new Matiere(1,nommat));
                }
                
                this.gererMatiere.affichage();
                this.dispose();
        
            } else if(p == JOptionPane.NO_OPTION) {

                this.dispose();
            } 
        } else {
            JOptionPane.showMessageDialog(null,"Le champ Nom de Matière est obligatoire!","Formulaire incomplet!", JOptionPane.QUESTION_MESSAGE, null);
        }
    }
    
    
    public void setGererMatiere(GererMatiere gm) {
        this.gererMatiere = gm;
      
       
    }//GEN-LAST:event_jButton1ActionPerformed
    public void setNomMatiereField(String nommatiere){
        
        
        this.matierefield.setText(nommatiere);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterMat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterMat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterMat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterMat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterMat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField matierefield;
    // End of variables declaration//GEN-END:variables
}
