/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.planning.view.AdminDept;

import com.planning.dao.implement.EnseignantDAO;
import com.planning.dao.implement.MatiereDAO;
import com.planning.model.ConnexionBD;
import com.planning.model.Enseignant;
import com.planning.model.Matiere;
import java.sql.Connection;
import java.util.ArrayList;

/**
 *
 * @author Azough Mehdi
 */
public class AjouterSeance extends javax.swing.JFrame {

    private ArrayList listens;
    private ArrayList listmat;
    private EnseignantDAO ensd;
    private Enseignant ens;
    private Matiere mat;
    private MatiereDAO matd;
    Connection conn = ConnexionBD.init();
    
    /**
     * Creates new form AjouterSeance
     */
    public AjouterSeance() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void init() {
        this.setTitle("Insertion d'une seance");
        ensd = new EnseignantDAO(conn);
        matd = new MatiereDAO(conn);
        listmat  = matd.FindAll();
        listens = ensd.findAll();
        for(int i = 0; i < listens.size(); i++) {
            ens = (Enseignant) listens.get(i);
            ensCombo.addItem(ens.getNomEns() + " "  + ens.getPrenomEns());
        }
        
        for(int i = 0; i < listmat.size(); i++) {
            mat = (Matiere) listmat.get(i);
            matiereCombo.addItem(mat.getNomMatiere());
        }
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matiereCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        ensCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        dateDChooser = new com.toedter.calendar.JDateChooser();
        dateFChooser = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enregistrer = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Matière");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(400, 360));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(matiereCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 180, 30));

        jLabel1.setText("Matière *");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 30));

        getContentPane().add(ensCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 180, 30));

        jLabel2.setText("Enseignant *");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 30));
        getContentPane().add(dateDChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 180, 30));
        getContentPane().add(dateFChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 180, 30));

        jLabel3.setText("Date Debut *");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel4.setText("Date fin *");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        enregistrer.setText("Enregistrer");
        enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerActionPerformed(evt);
            }
        });
        getContentPane().add(enregistrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 120, 30));

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(annulerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_enregistrerActionPerformed

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_annulerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterSeance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterSeance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterSeance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterSeance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterSeance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerButton;
    private com.toedter.calendar.JDateChooser dateDChooser;
    private com.toedter.calendar.JDateChooser dateFChooser;
    private javax.swing.JButton enregistrer;
    private javax.swing.JComboBox<String> ensCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> matiereCombo;
    // End of variables declaration//GEN-END:variables
}
