/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.planning.view.AdminDept;

import com.planning.dao.implement.EnseignantDAO;
import com.planning.dao.implement.FiliereDAO;
import com.planning.dao.implement.GroupeDAO;
import com.planning.dao.implement.UsersDAO;
import com.planning.model.ConnexionBD;
import com.planning.model.Groupe;
import javax.swing.JOptionPane;

/**
 *
 * @author Azough Mehdi
 */
public class Ajouter_Groupe extends javax.swing.JFrame {

    /**
     * Creates new form ajouter_modifier
     */
    public Ajouter_Groupe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indication = new javax.swing.JLabel();
        Confirmer = new javax.swing.JButton();
        nomgroupefield = new javax.swing.JTextField();
        ChoixFiliere = new javax.swing.JComboBox<>();
        ChoixNiveau = new javax.swing.JComboBox<>();
        NomGroupe = new javax.swing.JLabel();
        Filiere = new javax.swing.JLabel();
        Niveau = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajouter ");
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indication.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        indication.setText("Veuillez remplir les informations suivantes :");
        getContentPane().add(indication, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Confirmer.setText("Confirmer");
        Confirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmerActionPerformed(evt);
            }
        });
        getContentPane().add(Confirmer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 120, 30));

        nomgroupefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomgroupefieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomgroupefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 180, 30));

        ChoixFiliere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filiere" }));
        ChoixFiliere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoixFiliereActionPerformed(evt);
            }
        });
        getContentPane().add(ChoixFiliere, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 100, 30));

        ChoixNiveau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        ChoixNiveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoixNiveauActionPerformed(evt);
            }
        });
        getContentPane().add(ChoixNiveau, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 100, 30));

        NomGroupe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NomGroupe.setText("Nom groupe ");
        getContentPane().add(NomGroupe, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, 20));

        Filiere.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Filiere.setText("Filière :");
        getContentPane().add(Filiere, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        Niveau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Niveau.setText("Niveau :");
        getContentPane().add(Niveau, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmerActionPerformed
        int niveauChoix, numFiliere;
        
        FiliereDAO filiereDAO = new FiliereDAO(ConnexionBD.init());
        UsersDAO usersDAO = new UsersDAO(ConnexionBD.init());
        EnseignantDAO enseignantDAO = new EnseignantDAO(ConnexionBD.init());
        GroupeDAO groupeDAO = new GroupeDAO(ConnexionBD.init());
        
        String nomgroupe = new String(nomgroupefield.getText());
        String filiereChoix = new String();
        
        filiereChoix = ChoixFiliere.getSelectedItem().toString();
        niveauChoix = ChoixNiveau.getSelectedIndex();
        numFiliere = filiereDAO.findNumFiliere(filiereChoix);
        Groupe gp = new Groupe(10,numFiliere,nomgroupe,niveauChoix);
        groupeDAO.create(gp);
        JOptionPane.showMessageDialog(null, "Groupe ajouté avec succès");
        
    }//GEN-LAST:event_ConfirmerActionPerformed

    private void nomgroupefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomgroupefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomgroupefieldActionPerformed

    private void ChoixFiliereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoixFiliereActionPerformed

        
        //ChoixFiliere.addItem(item);
    }//GEN-LAST:event_ChoixFiliereActionPerformed

    private void ChoixNiveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoixNiveauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChoixNiveauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajouter_Groupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajouter_Groupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajouter_Groupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajouter_Groupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajouter_Groupe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ChoixFiliere;
    private javax.swing.JComboBox<String> ChoixNiveau;
    private javax.swing.JButton Confirmer;
    private javax.swing.JLabel Filiere;
    private javax.swing.JLabel Niveau;
    private javax.swing.JLabel NomGroupe;
    public javax.swing.JLabel indication;
    public javax.swing.JTextField nomgroupefield;
    // End of variables declaration//GEN-END:variables
}
