/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.planning.view.AdminDept;

import com.planning.dao.implement.FiliereDAO;
import com.planning.dao.implement.GroupeDAO;
import com.planning.model.ConnexionBD;
import com.planning.model.Filiere;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;

/**
 *
 * @author Azough Mehdi
 */
public class GererEmploi extends javax.swing.JInternalFrame {

    FiliereDAO filD;
    ArrayList  listefil;
    ResultSet res;
    Filiere fil;
    GroupeDAO groupedao;
    Connection conn = ConnexionBD.init();/**
     * Creates new form GererEmloi
     */
    public GererEmploi() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        this.getContentPane().setBackground(Color.white);
        this.setBorder(BorderFactory.createLineBorder(Color.black, 1));
         filD = new FiliereDAO(conn);
         groupedao = new GroupeDAO(conn);
        listefil=filD.findAll();
        for (int i = 0; i < listefil.size(); i++) {
            
            fil = (Filiere)listefil.get(i);
            filierecombo.addItem(fil.getNomFiliere());
            
        }
        res= groupedao.findALL();
        groupecombo.removeAllItems();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        l8 = new javax.swing.JPanel();
        l10 = new javax.swing.JPanel();
        l16 = new javax.swing.JPanel();
        l14 = new javax.swing.JPanel();
        ma8 = new javax.swing.JPanel();
        ma10 = new javax.swing.JPanel();
        ma14 = new javax.swing.JPanel();
        ma16 = new javax.swing.JPanel();
        j8 = new javax.swing.JPanel();
        me8 = new javax.swing.JPanel();
        me10 = new javax.swing.JPanel();
        j10 = new javax.swing.JPanel();
        j14 = new javax.swing.JPanel();
        me14 = new javax.swing.JPanel();
        me16 = new javax.swing.JPanel();
        j16 = new javax.swing.JPanel();
        v8 = new javax.swing.JPanel();
        v10 = new javax.swing.JPanel();
        v14 = new javax.swing.JPanel();
        v16 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        groupecombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        filierecombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        niveaucombo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("Gérer Emplois");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel2.setText("LUNDI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, 80));

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel3.setText("MARDI");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 130, 80));

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel4.setText("MERCREDI");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 130, 80));

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel5.setText("JEUDI");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 130, 80));

        jPanel5.setBackground(new java.awt.Color(102, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel6.setText("VENDREDI");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 130, 80));

        jPanel6.setBackground(new java.awt.Color(102, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel7.setText("8h-10h");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 140, 60));

        jPanel8.setBackground(new java.awt.Color(102, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel9.setText("14h-16h");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 150, 60));

        jPanel9.setBackground(new java.awt.Color(102, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel10.setText("16h-18h");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 150, 60));

        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l8MouseEntered(evt);
            }
        });
        getContentPane().add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 140, 80));

        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l10MouseClicked(evt);
            }
        });
        getContentPane().add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 150, 80));

        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l16MouseClicked(evt);
            }
        });
        getContentPane().add(l16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 150, 80));

        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l14MouseClicked(evt);
            }
        });
        getContentPane().add(l14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 150, 80));

        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ma8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ma8MouseClicked(evt);
            }
        });
        getContentPane().add(ma8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 140, 80));

        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ma10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ma10MouseClicked(evt);
            }
        });
        getContentPane().add(ma10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 150, 80));

        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ma14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ma14MouseClicked(evt);
            }
        });
        getContentPane().add(ma14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 150, 80));

        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ma16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ma16MouseClicked(evt);
            }
        });
        getContentPane().add(ma16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 150, 80));

        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j8MouseClicked(evt);
            }
        });
        getContentPane().add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 140, 80));

        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        me8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                me8MouseClicked(evt);
            }
        });
        getContentPane().add(me8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 140, 80));

        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        me10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                me10MouseClicked(evt);
            }
        });
        getContentPane().add(me10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 150, 80));

        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j10MouseClicked(evt);
            }
        });
        getContentPane().add(j10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 150, 80));

        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j14MouseClicked(evt);
            }
        });
        getContentPane().add(j14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 150, 80));

        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        me14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                me14MouseClicked(evt);
            }
        });
        getContentPane().add(me14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 150, 80));

        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        me16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                me16MouseClicked(evt);
            }
        });
        getContentPane().add(me16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 150, 80));

        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j16MouseClicked(evt);
            }
        });
        getContentPane().add(j16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 150, 80));

        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        v8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v8MouseClicked(evt);
            }
        });
        getContentPane().add(v8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 140, 80));

        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        v10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v10MouseClicked(evt);
            }
        });
        getContentPane().add(v10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 150, 80));

        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        v14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v14MouseClicked(evt);
            }
        });
        getContentPane().add(v14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 150, 80));

        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        v16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v16MouseClicked(evt);
            }
        });
        getContentPane().add(v16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 150, 80));

        jPanel7.setBackground(new java.awt.Color(102, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel8.setText("10h-12h");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 150, 60));

        groupecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupecomboActionPerformed(evt);
            }
        });
        getContentPane().add(groupecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 90, 30));

        jLabel1.setText("Filière");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        filierecombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filierecomboItemStateChanged(evt);
            }
        });
        getContentPane().add(filierecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, 30));

        jLabel11.setText("Niveau");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        niveaucombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        niveaucombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                niveaucomboItemStateChanged(evt);
            }
        });
        getContentPane().add(niveaucombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 90, 30));

        jLabel12.setText("Groupe");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        jButton1.setText("Définir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseClicked

        l8.setBackground(Color.gray);
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));

    }//GEN-LAST:event_l8MouseClicked

    private void l8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseEntered

    }//GEN-LAST:event_l8MouseEntered

    private void l10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l10MouseClicked
        l10.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_l10MouseClicked

    private void l16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l16MouseClicked
        l16.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_l16MouseClicked

    private void l14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l14MouseClicked
        l14.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_l14MouseClicked

    private void ma8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ma8MouseClicked
        ma8.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_ma8MouseClicked

    private void ma10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ma10MouseClicked
        ma10.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_ma10MouseClicked

    private void ma14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ma14MouseClicked
        ma14.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_ma14MouseClicked

    private void ma16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ma16MouseClicked
        ma16.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_ma16MouseClicked

    private void j8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j8MouseClicked
        j8.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_j8MouseClicked

    private void me8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_me8MouseClicked
        me8.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_me8MouseClicked

    private void me10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_me10MouseClicked
        me10.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_me10MouseClicked

    private void j10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j10MouseClicked
        j10.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_j10MouseClicked

    private void j14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j14MouseClicked
        j14.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_j14MouseClicked

    private void me14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_me14MouseClicked
        me14.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_me14MouseClicked

    private void me16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_me16MouseClicked
        me16.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_me16MouseClicked

    private void j16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j16MouseClicked
        j16.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_j16MouseClicked

    private void v8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v8MouseClicked
        v8.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_v8MouseClicked

    private void v10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v10MouseClicked
        v10.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_v10MouseClicked

    private void v14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v14MouseClicked
        v14.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_v14MouseClicked

    private void v16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v16MouseClicked
        v16.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_v16MouseClicked

    private void groupecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupecomboActionPerformed

    private void filierecomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filierecomboItemStateChanged
      res = groupedao.findALL();
      String etat = (String)filierecombo.getSelectedItem();
      int niveau = niveaucombo.getSelectedIndex()+1;
      groupecombo.removeAllItems();
        try {
            while(res.next()){
                
                if(etat.equals(res.getString(4))&&(niveau==res.getInt(5))){
                    groupecombo.addItem(res.getString(2));
                    System.out.println(res.getString(2));
                }
                
                    
            } } catch (SQLException ex) {
            Logger.getLogger(GererEmploi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_filierecomboItemStateChanged

    private void niveaucomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_niveaucomboItemStateChanged
      res = groupedao.findALL();
      String etat = (String)filierecombo.getSelectedItem();
      int niveau = niveaucombo.getSelectedIndex()+1;
      groupecombo.removeAllItems();
        try {
           
            while(res.next()){            
                if(etat.equals(res.getString(4))&&(niveau==res.getInt(5))){
                    groupecombo.addItem(res.getString(2));
                    System.out.println(res.getString(2));
                }
                
                    
            } } catch (SQLException ex) {
            Logger.getLogger(GererEmploi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_niveaucomboItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AjouterSeance().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> filierecombo;
    private javax.swing.JComboBox<String> groupecombo;
    private javax.swing.JPanel j10;
    private javax.swing.JPanel j14;
    private javax.swing.JPanel j16;
    private javax.swing.JPanel j8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel l10;
    private javax.swing.JPanel l14;
    private javax.swing.JPanel l16;
    private javax.swing.JPanel l8;
    private javax.swing.JPanel ma10;
    private javax.swing.JPanel ma14;
    private javax.swing.JPanel ma16;
    private javax.swing.JPanel ma8;
    private javax.swing.JPanel me10;
    private javax.swing.JPanel me14;
    private javax.swing.JPanel me16;
    private javax.swing.JPanel me8;
    private javax.swing.JComboBox<String> niveaucombo;
    private javax.swing.JPanel v10;
    private javax.swing.JPanel v14;
    private javax.swing.JPanel v16;
    private javax.swing.JPanel v8;
    // End of variables declaration//GEN-END:variables
}
