/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.planning.view.AdminDept;

import com.planning.dao.implement.FiliereDAO;
import com.planning.dao.implement.GroupeDAO;
import com.planning.dao.implement.GrpMatDAO;
import com.planning.dao.implement.StatiqCrenoDAO;
import com.planning.model.ConnexionBD;
import com.planning.model.Filiere;
import com.planning.model.GroupeMatiere;
import com.planning.model.StatiqueCreneau;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Azough Mehdi
 */
public class GererEmploi extends javax.swing.JInternalFrame {

    FiliereDAO filD;
    ArrayList  listefil;
    ResultSet res;
    Filiere fil;
    GroupeDAO groupedao;
    Connection conn = ConnexionBD.init();
    int numpan = -1;
    StatiqueCreneau emp[][] = new StatiqueCreneau[5][4];
    AcceuilAdminDept aadept;
    MonCompteDept compteDept;
    

    /**
     * Creates new form GererEmloi
     */
    public GererEmploi() {
        initComponents();
        init();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupecombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        filierecombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        niveaucombo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        definirSeance = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        l8 = new javax.swing.JPanel();
        l8text = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        l10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        l16 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        l14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        ma8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        ma10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ma14 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        ma16 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        j8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        me8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        me10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        j10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        j14 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        me14 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        me16 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        j16 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        v8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        v10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        v14 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        v16 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        supprimerButton = new javax.swing.JButton();

        setTitle("Gestion des Emplois du temps");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        groupecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GA", "GB" }));
        groupecombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                groupecomboItemStateChanged(evt);
            }
        });
        groupecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupecomboActionPerformed(evt);
            }
        });
        getContentPane().add(groupecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 70, 30));

        jLabel1.setText("Filière");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        filierecombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filierecomboItemStateChanged(evt);
            }
        });
        getContentPane().add(filierecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, 30));

        jLabel11.setText("Niveau");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        niveaucombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        niveaucombo.setSelectedIndex(-1);
        niveaucombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                niveaucomboItemStateChanged(evt);
            }
        });
        getContentPane().add(niveaucombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 50, 30));

        jLabel12.setText("Groupe");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        definirSeance.setText("Ajouter une seance");
        definirSeance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                definirSeanceActionPerformed(evt);
            }
        });
        getContentPane().add(definirSeance, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 160, 30));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel2.setText("LUNDI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 130, 80));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel3.setText("MARDI");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 130, 80));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel4.setText("MERCREDI");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 130, 80));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel5.setText("JEUDI");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 130, 80));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel6.setText("VENDREDI");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, 80));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel7.setText("8h-10h");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 140, 60));

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel9.setText("14h-16h");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 150, 60));

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(0, 153, 153));
        jLabel10.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel10.setText("16h-18h");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 150, 60));

        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l8MouseEntered(evt);
            }
        });
        l8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l8text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l8text.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                l8textComponentResized(evt);
            }
        });
        l8text.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                l8textInputMethodTextChanged(evt);
            }
        });
        l8text.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                l8textPropertyChange(evt);
            }
        });
        l8.add(l8text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setToolTipText("");
        jLabel32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        l8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 20));

        getContentPane().add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 140, 80));

        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l10MouseClicked(evt);
            }
        });
        l10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setToolTipText("");
        l10.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 150, 80));

        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l16MouseClicked(evt);
            }
        });
        l16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l16.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l16.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(l16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 150, 80));

        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l14MouseClicked(evt);
            }
        });
        l14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l14.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l14.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(l14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 150, 80));

        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ma8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ma8MouseClicked(evt);
            }
        });
        ma8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ma8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ma8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 20));

        getContentPane().add(ma8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 140, 80));

        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ma10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ma10MouseClicked(evt);
            }
        });
        ma10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ma10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setToolTipText("");
        ma10.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(ma10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 150, 80));

        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ma14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ma14MouseClicked(evt);
            }
        });
        ma14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ma14.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ma14.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(ma14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 150, 80));

        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ma16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ma16MouseClicked(evt);
            }
        });
        ma16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ma16.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ma16.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(ma16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 150, 80));

        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j8MouseClicked(evt);
            }
        });
        j8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j8.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 20));

        getContentPane().add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 140, 80));

        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        me8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                me8MouseClicked(evt);
            }
        });
        me8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 20));

        getContentPane().add(me8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 140, 80));

        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        me10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                me10MouseClicked(evt);
            }
        });
        me10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me10.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(me10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 150, 80));

        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j10MouseClicked(evt);
            }
        });
        j10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j10.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(j10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 150, 80));

        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j14MouseClicked(evt);
            }
        });
        j14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabel26InputMethodTextChanged(evt);
            }
        });
        j14.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j14.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(j14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 150, 80));

        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        me14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                me14MouseClicked(evt);
            }
        });
        me14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(me14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 150, 80));

        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        me16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                me16MouseClicked(evt);
            }
        });
        me16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me16.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me16.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(me16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 150, 80));

        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j16MouseClicked(evt);
            }
        });
        j16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j16.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j16.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(j16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 150, 80));

        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        v8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v8MouseClicked(evt);
            }
        });
        v8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v8.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 20));

        getContentPane().add(v8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 140, 80));

        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        v10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v10MouseClicked(evt);
            }
        });
        v10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v10.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v10.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(v10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 150, 80));

        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        v14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v14MouseClicked(evt);
            }
        });
        v14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v14.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v14.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(v14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 150, 80));

        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        v16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v16MouseClicked(evt);
            }
        });
        v16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v16.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v16.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(v16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 150, 80));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel8.setText("10h-12h");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 150, 60));

        supprimerButton.setText("Supprimer");
        supprimerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(supprimerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void init() {
        
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        this.getContentPane().setBackground(Color.white);
        this.setBorder(BorderFactory.createLineBorder(Color.black, 1));
        filD = new FiliereDAO(conn);
        groupedao = new GroupeDAO(conn);
        listefil=filD.findAll();
        
        for (int i = 0; i < listefil.size(); i++) {
            fil = (Filiere) listefil.get(i);
            filierecombo.addItem(fil.getNomFiliere());
        }
        res = groupedao.findALL();
        groupecombo.removeAllItems();
        filierecombo.setSelectedIndex(-1);
        //this.filierecomboItemStateChanged(null);
    }
    
    public void setAcceuilAdminDept(AcceuilAdminDept aadept) {
        this.aadept = aadept;
    }
    private void groupecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupecomboActionPerformed

    private void filierecomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filierecomboItemStateChanged
        if(filierecombo.getSelectedIndex() == -1) return;
        res = groupedao.findALL();
        String filname = (String)filierecombo.getSelectedItem();
        int niveau = niveaucombo.getSelectedIndex()+1;
        groupecombo.removeAllItems();
        int numGroupe = 0;
        try {
            while(res.next()){
                
                if(filname.equals(res.getString(4)) && (niveau==res.getInt(5))){
                    groupecombo.addItem(res.getString(2));
                    if(numGroupe == 0) numGroupe = res.getInt(1);
                }
                
                    
            } } catch (SQLException ex) {
            Logger.getLogger(GererEmploi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_filierecomboItemStateChanged

    private void niveaucomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_niveaucomboItemStateChanged
      res = groupedao.findALL();
      String etat = (String)filierecombo.getSelectedItem();
      int niveau = niveaucombo.getSelectedIndex()+1;
      groupecombo.removeAllItems();
      int numGroupe = 0;
        try {
           
            while(res.next()){            
                if(etat.equals(res.getString(4))&&(niveau==res.getInt(5))){
                    groupecombo.addItem(res.getString(2));
                    if(numGroupe == 0) numGroupe = res.getInt(1);
                }
                
                    
            } } catch (SQLException ex) {
            Logger.getLogger(GererEmploi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_niveaucomboItemStateChanged

    private void definirSeanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_definirSeanceActionPerformed
        
        if(numpan == -1) {
            JOptionPane.showMessageDialog(null, "Selectionnez un creneau!", "Emploi du temps", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(niveaucombo.getSelectedIndex() == -1 || groupecombo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Selectionnez un groupe", "Emploi du temps", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        res = groupedao.findALL();
        String filname = (String)filierecombo.getSelectedItem();
        int niveau = niveaucombo.getSelectedIndex()+1;
        String groupename = (String) groupecombo.getSelectedItem();
        int numGroupe = 0;
        try {
            while(res.next()){
                
                if(filname.equals(res.getString(4)) && (niveau == res.getInt(5)) && groupename.equals(res.getString(2))){
                    numGroupe = res.getInt(1);
                    break;
                }
                 
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(GererEmploi.class.getName()).log(Level.SEVERE, null, ex);
        }
                            
        this.getEmp(numGroupe);
        AjouterSeance ajouterSeance = new AjouterSeance();
        ajouterSeance.setNumGroupe(numGroupe);
        
         switch(numpan){
            case 1: 
                ajouterSeance.setJourSemaine(2);
                ajouterSeance.setHeureSeance("08:00:00");
                break;
            case 2: 
                ajouterSeance.setJourSemaine(2);
                ajouterSeance.setHeureSeance("10:00:00");
                break;
            case 3: 
                ajouterSeance.setJourSemaine(2);
                ajouterSeance.setHeureSeance("14:00:00");
                break;
            case 4: 
                ajouterSeance.setJourSemaine(2);
                ajouterSeance.setHeureSeance("16:00:00");
                break;
            case 5: 
                ajouterSeance.setJourSemaine(3);
                ajouterSeance.setHeureSeance("08:00:00");
                break;
            case 6: 
                ajouterSeance.setJourSemaine(3);
                ajouterSeance.setHeureSeance("10:00:00");
                break;
            case 7: 
                ajouterSeance.setJourSemaine(3);
                ajouterSeance.setHeureSeance("14:00:00");
                break;
            case 8: 
                ajouterSeance.setJourSemaine(3);
                ajouterSeance.setHeureSeance("16:00:00");
                break;
            case 9: 
                ajouterSeance.setJourSemaine(4);
                ajouterSeance.setHeureSeance("08:00:00");
                break;
            case 10: 
                ajouterSeance.setJourSemaine(4);
                ajouterSeance.setHeureSeance("10:00:00");
                break;
            case 11: 
                ajouterSeance.setJourSemaine(4);
                ajouterSeance.setHeureSeance("14:00:00");
                break;
            case 12: 
                ajouterSeance.setJourSemaine(4);
                ajouterSeance.setHeureSeance("16:00:00");
                break;
            case 13: 
                ajouterSeance.setJourSemaine(5);
                ajouterSeance.setHeureSeance("08:00:00");
                break;
            case 14: 
                ajouterSeance.setJourSemaine(5);
                ajouterSeance.setHeureSeance("10:00:00");
                break;
            case 15: 
                ajouterSeance.setJourSemaine(5);
                ajouterSeance.setHeureSeance("14:00:00");
                break;
            case 16: 
                ajouterSeance.setJourSemaine(5);
                ajouterSeance.setHeureSeance("16:00:00");
                break;
            case 17: 
                ajouterSeance.setJourSemaine(6);
                ajouterSeance.setHeureSeance("08:00:00");
                break;
            case 18: 
                ajouterSeance.setJourSemaine(6);
                ajouterSeance.setHeureSeance("10:00:00");
                break;
            case 19: 
                ajouterSeance.setJourSemaine(6);
                ajouterSeance.setHeureSeance("14:00:00");
                break;
            case 20: 
                ajouterSeance.setJourSemaine(6);
                ajouterSeance.setHeureSeance("16:00:00");
                break;
            default: 
                //JOptionPane.showMessageDialog(this, "Selectionnez un creneau!", "Emploi du temps", JOptionPane.INFORMATION_MESSAGE);
                break;    
        }
         
        ajouterSeance.setGererEmploi(this);
        ajouterSeance.setVisible(true);
    }//GEN-LAST:event_definirSeanceActionPerformed
    
    public void getEmp(int numGroupe) {
        this.resetEMP();
        StatiqCrenoDAO scdao = new StatiqCrenoDAO(conn);
        ArrayList listensmat = scdao.findAllByNumGroupe(numGroupe);
        StatiqueCreneau sc;
        int jourS;
        String heureS;
        if(listensmat == null) {
            return;
        }
        
        for (int i = 0; i < listensmat.size(); i++) {
            sc = (StatiqueCreneau) listensmat.get(i);
            jourS = sc.getJourSemaine();
            heureS = sc.getHeureSeance().toString();
                if(String.valueOf(jourS).equals("2")) {

                    if(heureS.equals("08:00:00")) {
                        emp[0][0] = sc;
                        l8text.setText(sc.getNomMatiere());
                        jLabel32.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }
                   
                    else if(heureS.equals("10:00:00")) {
                        emp[0][1] = sc;
                        jLabel13.setText(sc.getNomMatiere());
                        jLabel33.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }
                    else if(heureS.equals("14:00:00")) {
                        emp[0][2] = sc;
                        jLabel14.setText(sc.getNomMatiere());
                        jLabel34.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }
                    else {
                        emp[0][3] = sc;
                        jLabel15.setText(sc.getNomMatiere());
                        jLabel35.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }
                }

                else if(String.valueOf(jourS).equals("3")) {
                    if(heureS.equals("08:00:00")) {
                        emp[1][0] = sc;
                        jLabel16.setText(sc.getNomMatiere());
                        jLabel36.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }

                    else if(heureS.equals("10:00:00")) {
                        emp[1][1] = sc;
                        jLabel17.setText(sc.getNomMatiere());
                        jLabel37.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }
                    else if(heureS.equals("14:00:00")) {
                        emp[1][2] = sc;
                        jLabel18.setText(sc.getNomMatiere());
                        jLabel38.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }
                    else {
                        emp[1][3] = sc;
                        jLabel19.setText(sc.getNomMatiere());
                        jLabel39.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }
                }

                else if(String.valueOf(jourS).equals("4")) {
                    if(heureS.equals("08:00:00")) {
                        emp[2][0] = sc;
                        jLabel20.setText(sc.getNomMatiere());
                        jLabel40.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }

                    else if(heureS.equals("10:00:00")) {
                        emp[2][1] = sc;
                        jLabel21.setText(sc.getNomMatiere());
                        jLabel41.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }
                    else if(heureS.equals("14:00:00")) {
                        emp[2][2] = sc;
                        jLabel22.setText(sc.getNomMatiere());
                        jLabel42.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }
                    else {
                        emp[2][3] = sc;
                        jLabel23.setText(sc.getNomMatiere());
                        jLabel43.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }
                }

                else if(String.valueOf(jourS).equals("5")) {
                    if(heureS.equals("08:00:00")) {
                        emp[3][0] = sc;
                        jLabel24.setText(sc.getNomMatiere());
                        jLabel44.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }

                    else if(heureS.equals("10:00:00")) {
                        emp[3][1] = sc;
                        jLabel25.setText(sc.getNomMatiere());
                        jLabel45.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }
                    else if(heureS.equals("14:00:00")) {
                        emp[3][2] = sc;
                        jLabel26.setText(sc.getNomMatiere());
                        jLabel46.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                 
                        jLabel26.paintImmediately(jLabel26.getVisibleRect());
                        jLabel46.paintImmediately(jLabel46.getVisibleRect());
                    }
                    else {
                        emp[3][3] = sc;
                        jLabel27.setText(sc.getNomMatiere());
                        jLabel47.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }
                }

                else if (String.valueOf(jourS).equals("6")) {
                    if(heureS.equals("08:00:00")) {
                        emp[4][0] = sc;
                        jLabel28.setText(sc.getNomMatiere());
                        jLabel48.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }

                    else if(heureS.equals("10:00:00")) {
                        emp[4][1] = sc;
                        jLabel29.setText(sc.getNomMatiere());
                        jLabel49.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }
                    else if(heureS.equals("14:00:00")) {
                        emp[4][2] = sc;
                        jLabel30.setText(sc.getNomMatiere());
                        jLabel50.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }
                    else {
                        emp[4][3] = sc;
                        jLabel31.setText(sc.getNomMatiere());
                        jLabel51.setText(sc.getNomEns() + " " + sc.getPrenomEns());
                    }
                }

                else {
                   
                }

        }
        
        
        
    }
    
    public void resetEMP() {
        l8text.setText(null);
        jLabel32.setText(null);

        jLabel13.setText(null);
        jLabel33.setText(null);

        jLabel14.setText(null);
        jLabel34.setText(null);

        jLabel15.setText(null);
        jLabel35.setText(null);

        jLabel16.setText(null);
        jLabel36.setText(null);

        jLabel17.setText(null);
        jLabel37.setText(null);

        jLabel18.setText(null);
        jLabel38.setText(null);

        jLabel19.setText(null);
        jLabel39.setText(null);

        jLabel20.setText(null);
        jLabel40.setText(null);

        jLabel21.setText(null);
        jLabel41.setText(null);

        jLabel22.setText(null);
        jLabel42.setText(null);

        jLabel23.setText(null);
        jLabel43.setText(null);

        jLabel24.setText(null);
        jLabel44.setText(null);

        jLabel25.setText(null);
        jLabel45.setText(null);

        jLabel26.setText(null);
        jLabel46.setText(null);

        jLabel27.setText(null);
        jLabel47.setText(null);

        jLabel28.setText(null);
        jLabel48.setText(null);

        jLabel29.setText(null);
        jLabel49.setText(null);

        jLabel30.setText(null);
        jLabel50.setText(null);

        jLabel31.setText(null);
        jLabel51.setText(null);

    }
    
    private void l8textComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_l8textComponentResized
        // TODO add your handling code here:
       

    }//GEN-LAST:event_l8textComponentResized

    private void l8textInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_l8textInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_l8textInputMethodTextChanged

    private void l8textPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_l8textPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_l8textPropertyChange

    private void l8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseClicked
        numpan = 1;

        l8.setBackground(Color.gray);
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));

    }//GEN-LAST:event_l8MouseClicked

    private void l8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseEntered

    }//GEN-LAST:event_l8MouseEntered

    private void l10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l10MouseClicked
        numpan = 2;
        l10.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_l10MouseClicked

    private void l16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l16MouseClicked
        numpan = 4;
        l16.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_l16MouseClicked

    private void l14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l14MouseClicked
        numpan = 3;
        l14.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_l14MouseClicked

    private void ma8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ma8MouseClicked
        numpan = 5;
        ma8.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_ma8MouseClicked

    private void ma10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ma10MouseClicked
        numpan = 6;
        ma10.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_ma10MouseClicked

    private void ma14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ma14MouseClicked
        numpan = 7;
        ma14.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_ma14MouseClicked

    private void ma16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ma16MouseClicked
        numpan = 8;
        ma16.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_ma16MouseClicked

    private void j8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j8MouseClicked
        numpan = 13;
        j8.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_j8MouseClicked

    private void me8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_me8MouseClicked
        numpan = 9;
        me8.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_me8MouseClicked

    private void me10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_me10MouseClicked
        numpan = 10;
        me10.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_me10MouseClicked

    private void j10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j10MouseClicked
        numpan = 14;
        j10.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_j10MouseClicked

    private void jLabel26InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel26InputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel26InputMethodTextChanged

    private void j14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j14MouseClicked
        numpan = 15;
        j14.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_j14MouseClicked

    private void me14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_me14MouseClicked
        numpan = 11;
        me14.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_me14MouseClicked

    private void me16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_me16MouseClicked
        numpan = 12;
        me16.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_me16MouseClicked

    private void j16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j16MouseClicked
        numpan = 16;
        j16.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_j16MouseClicked

    private void v8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v8MouseClicked
        numpan = 17;
        v8.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_v8MouseClicked

    private void v10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v10MouseClicked
        numpan = 18;
        v10.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_v10MouseClicked

    private void v14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v14MouseClicked
        numpan = 19;
        v14.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_v14MouseClicked

    private void v16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v16MouseClicked
        numpan = 20;
        v16.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        
    }//GEN-LAST:event_v16MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        numpan = -1;
    }//GEN-LAST:event_formMouseClicked

    private void groupecomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_groupecomboItemStateChanged
        // TODO add your handling code here:
        if(groupecombo.getSelectedIndex() == -1) return;
        res = groupedao.findALL();
        String filname = (String)filierecombo.getSelectedItem();
        int niveau = niveaucombo.getSelectedIndex()+1;
        String groupename = (String) groupecombo.getSelectedItem();
        int numGroupe = 0;
        try {
            while(res.next()){
                
                if(filname.equals(res.getString(4)) && (niveau == res.getInt(5)) && groupename.equals(res.getString(2))){
                    numGroupe = res.getInt(1);
                    break;
                }
                 
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(GererEmploi.class.getName()).log(Level.SEVERE, null, ex);
        }
                            
        this.getEmp(numGroupe);
        
    }//GEN-LAST:event_groupecomboItemStateChanged
    
    private void supprimerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerButtonActionPerformed
        // TODO add your handling code here:
        if(numpan == -1) {
            JOptionPane.showMessageDialog(null, "Choisissez un creneau!", "Emploi du temps", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int p = JOptionPane.showConfirmDialog(null,"Etes-vous sur de vouloir supprimer?","Confirmation",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null);
            
        if(p == JOptionPane.NO_OPTION){
            return;
        }
        StatiqueCreneau sc; 
        
        switch(numpan){
            case 1: 
                sc = emp[0][0];
                break;
            case 2: 
                sc = emp[0][1];
                break;
            case 3: 
                sc = emp[0][2];
                break;
            case 4: 
                sc = emp[0][3];
                break;
            case 5: 
                sc = emp[1][0];
                break;
            case 6: 
                sc = emp[1][1];
                break;
            case 7: 
                sc = emp[1][2];
                break;
            case 8: 
                sc = emp[1][3];
                break;
            case 9: 
                sc = emp[2][0];
                break;
            case 10: 
                sc = emp[2][1];
                break;
            case 11: 
                sc = emp[2][2];
                break;
            case 12: 
                sc  = emp[2][3];
                break;
            case 13: 
                sc = emp[3][0];
                break;
            case 14: 
                sc = emp[3][1];
                break;
            case 15: 
                sc  = emp[3][2];
                break;
            case 16: 
                sc = emp[3][3];
                break;
            case 17: 
                sc = emp[4][0];
                break;
            case 18: 
                sc = emp[4][1];
                break;
            case 19: 
                sc = emp[4][2];
                break;
            case 20: 
                sc = emp[4][3];
                break;
            default:
                return;    
        }
        
        StatiqCrenoDAO scdao = new StatiqCrenoDAO(conn);
        scdao.delete(sc);
//        GrpMatDAO grpMatDAO = new GrpMatDAO(conn);
//        grpMatDAO.delete(new GroupeMatiere(sc.getNumMatiere(), sc.getNumGroupe()));
        
        this.getEmp(sc.getNumGroupe());
        
        
    }//GEN-LAST:event_supprimerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton definirSeance;
    private javax.swing.JComboBox<String> filierecombo;
    private javax.swing.JComboBox<String> groupecombo;
    private javax.swing.JPanel j10;
    private javax.swing.JPanel j14;
    private javax.swing.JPanel j16;
    private javax.swing.JPanel j8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel l10;
    private javax.swing.JPanel l14;
    private javax.swing.JPanel l16;
    private javax.swing.JPanel l8;
    private javax.swing.JLabel l8text;
    private javax.swing.JPanel ma10;
    private javax.swing.JPanel ma14;
    private javax.swing.JPanel ma16;
    private javax.swing.JPanel ma8;
    private javax.swing.JPanel me10;
    private javax.swing.JPanel me14;
    private javax.swing.JPanel me16;
    private javax.swing.JPanel me8;
    private javax.swing.JComboBox<String> niveaucombo;
    private javax.swing.JButton supprimerButton;
    private javax.swing.JPanel v10;
    private javax.swing.JPanel v14;
    private javax.swing.JPanel v16;
    private javax.swing.JPanel v8;
    // End of variables declaration//GEN-END:variables
}
