/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.planning.view.Enseignant;

/**
 *
 * @author Azough Mehdi
 */
public class MonEmploiEnseignant extends javax.swing.JInternalFrame {

    /**
     * Creates new form MonEmploi
     */
    public MonEmploiEnseignant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTitle("mon emploi");
        setMaximumSize(new java.awt.Dimension(860, 570));
        setMinimumSize(new java.awt.Dimension(860, 580));
        setPreferredSize(new java.awt.Dimension(860, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
