/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.planning.view.Enseignant;

import com.planning.controler.ConsulterEMP;
import com.planning.dao.implement.EnseignantDAO;
import com.planning.model.ConnexionBD;
import com.planning.model.Enseignant;
import com.planning.model.Seance;
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Azough Mehdi
 */
public class MonEmploiEnseignant extends javax.swing.JInternalFrame {

    /**
     * Creates new form MonEmploi
     */
    public void setAE(AcceuilEnseignant ae){
        this.ae = ae;
    }
    
    public MonEmploiEnseignant() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        this.getContentPane().setBackground(Color.white);
        this.setBorder(BorderFactory.createLineBorder(Color.black, 1));
        this.initEmp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        l8 = new javax.swing.JPanel();
        l8text = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        l10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        l16 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        l14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        ma8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        ma10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ma14 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        ma16 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        j8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        me8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        me10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        j10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        j14 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        me14 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        me16 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        j16 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        v8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        v10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        v14 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        v16 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        consulter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("mon emploi");
        setMaximumSize(new java.awt.Dimension(860, 570));
        setMinimumSize(new java.awt.Dimension(860, 580));
        setPreferredSize(new java.awt.Dimension(860, 570));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel2.setText("LUNDI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 130, 80));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel3.setText("MARDI");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 130, 80));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel4.setText("MERCREDI");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 130, 80));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel5.setText("JEUDI");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 130, 80));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel6.setText("VENDREDI");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 130, 80));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel7.setText("8h-10h");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 140, 60));

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel9.setText("14h-16h");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 150, 60));

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(0, 153, 153));
        jLabel10.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel10.setText("16h-18h");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 150, 60));

        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l8MouseEntered(evt);
            }
        });
        l8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l8text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l8text.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                l8textComponentResized(evt);
            }
        });
        l8text.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                l8textInputMethodTextChanged(evt);
            }
        });
        l8text.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                l8textPropertyChange(evt);
            }
        });
        l8.add(l8text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setToolTipText("");
        jLabel32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        l8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 20));

        getContentPane().add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 140, 80));

        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l10MouseClicked(evt);
            }
        });
        l10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setToolTipText("");
        l10.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 150, 80));

        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l16MouseClicked(evt);
            }
        });
        l16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l16.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l16.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(l16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 150, 80));

        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l14MouseClicked(evt);
            }
        });
        l14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l14.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l14.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(l14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 150, 80));

        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ma8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ma8MouseClicked(evt);
            }
        });
        ma8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ma8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ma8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 20));

        getContentPane().add(ma8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 140, 80));

        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ma10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ma10MouseClicked(evt);
            }
        });
        ma10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ma10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setToolTipText("");
        ma10.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(ma10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 150, 80));

        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ma14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ma14MouseClicked(evt);
            }
        });
        ma14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ma14.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ma14.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(ma14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 150, 80));

        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ma16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ma16MouseClicked(evt);
            }
        });
        ma16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ma16.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ma16.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(ma16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 150, 80));

        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j8MouseClicked(evt);
            }
        });
        j8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j8.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 20));

        getContentPane().add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 140, 80));

        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        me8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                me8MouseClicked(evt);
            }
        });
        me8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 20));

        getContentPane().add(me8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 140, 80));

        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        me10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                me10MouseClicked(evt);
            }
        });
        me10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me10.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(me10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 150, 80));

        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j10MouseClicked(evt);
            }
        });
        j10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j10.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(j10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 150, 80));

        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j14MouseClicked(evt);
            }
        });
        j14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabel26InputMethodTextChanged(evt);
            }
        });
        j14.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j14.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(j14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 150, 80));

        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        me14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                me14MouseClicked(evt);
            }
        });
        me14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(me14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 150, 80));

        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        me16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                me16MouseClicked(evt);
            }
        });
        me16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me16.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        me16.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(me16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 150, 80));

        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j16MouseClicked(evt);
            }
        });
        j16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j16.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j16.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(j16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 150, 80));

        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        v8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v8MouseClicked(evt);
            }
        });
        v8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v8.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 20));

        getContentPane().add(v8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 140, 80));

        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        v10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v10MouseClicked(evt);
            }
        });
        v10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v10.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v10.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(v10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 150, 80));

        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        v14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v14MouseClicked(evt);
            }
        });
        v14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v14.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v14.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(v14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 150, 80));

        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        v16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v16MouseClicked(evt);
            }
        });
        v16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v16.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 130, 20));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v16.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        getContentPane().add(v16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 150, 80));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Reporter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 123, 32));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel8.setText("10h-12h");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 150, 60));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 280, 30));

        consulter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        consulter.setText("Consulter");
        consulter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulterActionPerformed(evt);
            }
        });
        getContentPane().add(consulter, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 120, 30));

        jLabel1.setFont(new java.awt.Font("Vivaldi", 2, 48)); // NOI18N
        jLabel1.setText("Emploi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 120, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseEntered
        
    }//GEN-LAST:event_l8MouseEntered
    private int numpan = -1;
    
    private void l8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseClicked
        numpan = 1;
        l8.setBackground(Color.gray);
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        
        
    }//GEN-LAST:event_l8MouseClicked

    private void l10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l10MouseClicked
        numpan = 2;
        l10.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_l10MouseClicked

    private void l14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l14MouseClicked
        numpan = 3;
        l14.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_l14MouseClicked

    private void l16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l16MouseClicked
        numpan = 4;
        l16.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_l16MouseClicked

    private void ma8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ma8MouseClicked
        numpan = 5;
        ma8.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_ma8MouseClicked

    private void ma10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ma10MouseClicked
        numpan = 6;
        ma10.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_ma10MouseClicked

    private void ma14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ma14MouseClicked
        numpan = 7;
        ma14.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_ma14MouseClicked

    private void ma16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ma16MouseClicked
        numpan = 8;
        ma16.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_ma16MouseClicked

    private void me8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_me8MouseClicked
        numpan = 9;
        me8.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_me8MouseClicked

    private void me10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_me10MouseClicked
        numpan = 10;
        me10.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_me10MouseClicked

    private void me14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_me14MouseClicked
        numpan = 11;
        me14.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_me14MouseClicked

    private void me16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_me16MouseClicked
        numpan = 12;
        me16.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_me16MouseClicked

    private void j8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j8MouseClicked
        numpan = 13;
        j8.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_j8MouseClicked

    private void j10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j10MouseClicked
        numpan = 14;
        j10.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_j10MouseClicked

    private void j14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j14MouseClicked
        numpan = 15;
        j14.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_j14MouseClicked

    private void j16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j16MouseClicked
        numpan = 16;
        j16.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_j16MouseClicked

    private void v8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v8MouseClicked
        numpan = 17;
        v8.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_v8MouseClicked

    private void v14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v14MouseClicked
        numpan = 19;
        v14.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_v14MouseClicked

    private void v16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v16MouseClicked
        numpan = 20;
        v16.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_v16MouseClicked

    private void v10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v10MouseClicked
        numpan = 18;
        v10.setBackground(Color.gray);
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_v10MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        numpan = -1;
        v16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ma16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        me16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        j16.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        v14.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        l10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    }//GEN-LAST:event_formMouseClicked

    private void consulterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulterActionPerformed
        // TODO add your handling code here:
        
        Date dateSemaine = new Date(jDateChooser1.getDate().getTime());
        dateSemaine = this.getMonday(dateSemaine);
        Date semaineFin = this.getFriday(dateSemaine);
        this.getEmp(dateSemaine, semaineFin);

    }//GEN-LAST:event_consulterActionPerformed

    private void l8textInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_l8textInputMethodTextChanged
        // TODO add your handling code here:
 
    }//GEN-LAST:event_l8textInputMethodTextChanged

    private void jLabel26InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel26InputMethodTextChanged
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jLabel26InputMethodTextChanged

    private void l8textPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_l8textPropertyChange
        // TODO add your handling code here:
   
    }//GEN-LAST:event_l8textPropertyChange

    private void l8textComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_l8textComponentResized
        // TODO add your handling code here:
       
    }//GEN-LAST:event_l8textComponentResized

    private SeanceRattrapage srat;
    private AcceuilEnseignant ae;
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        srat = new SeanceRattrapage();
        switch(numpan){
            case 1: 
                this.srat.setnumseance(emp[0][0]);
                this.l8.setBackground(Color.red);
                /*Seance seance1 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance1);*/
                break;
            case 2: 
                this.srat.setnumseance(emp[0][1]);
                this.l10.setBackground(Color.red);
                /*Seance seance2 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance2);*/
                break;
            case 3: 
                this.srat.setnumseance(emp[0][2]);
                this.l14.setBackground(Color.red);
                /*Seance seance3 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance3);*/
                break;
            case 4: 
                this.srat.setnumseance(emp[0][3]);
                this.l16.setBackground(Color.red);
                /*Seance seance4 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance4);*/
                break;
            case 5: 
                this.srat.setnumseance(emp[1][0]);
                this.ma8.setBackground(Color.red);
                /*Seance seance5 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance5);*/
                break;
            case 6: 
                this.srat.setnumseance(emp[1][1]);
                this.ma10.setBackground(Color.red);
                /*Seance seance6 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance6);*/
                break;
            case 7: 
                this.srat.setnumseance(emp[1][2]);
                this.ma14.setBackground(Color.red);
                /*Seance seance7 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance7);*/
                break;
            case 8: 
                this.srat.setnumseance(emp[1][3]);
                this.ma16.setBackground(Color.red);
                /*Seance seance8 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance8);*/
                break;
            case 9: 
                this.srat.setnumseance(emp[2][0]);
                this.me8.setBackground(Color.red);
                /*Seance seance9 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance9);*/
                break;
            case 10: 
                this.srat.setnumseance(emp[2][1]);
                this.me10.setBackground(Color.red);
                /*Seance seance10 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance10);*/
                break;
            case 11: 
                this.srat.setnumseance(emp[2][2]);
                this.me14.setBackground(Color.red);
                /*Seance seance11 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance11);*/
                break;
            case 12: 
                this.srat.setnumseance(emp[2][3]);
                this.me16.setBackground(Color.red);
                /*Seance seance12 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance12);*/
                break;
            case 13: 
                this.srat.setnumseance(emp[3][0]);
                this.j8.setBackground(Color.red);
                /*Seance seance13 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance13);*/
                break;
            case 14: 
                this.srat.setnumseance(emp[3][1]);
                this.j10.setBackground(Color.red);
                /*Seance seance14 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance14);*/
                break;
            case 15: 
                this.srat.setnumseance(emp[3][2]);
                this.j14.setBackground(Color.red);
                /*Seance seance15 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance15);*/
                break;
            case 16: 
                this.srat.setnumseance(emp[3][3]);
                this.j16.setBackground(Color.red);
                /*Seance seance16 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance16);*/
                break;
            case 17: 
                this.srat.setnumseance(emp[4][0]);
                this.v8.setBackground(Color.red);
                /*Seance seance17 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance17);*/
                break;
            case 18: 
                this.srat.setnumseance(emp[4][1]);
                this.v10.setBackground(Color.red);
                /*Seance seance18 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance18);*/
                break;
            case 19: 
                this.srat.setnumseance(emp[4][2]);
                this.v14.setBackground(Color.red);
                /*Seance seance19 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance19);*/
                break;
            case 20: 
                this.srat.setnumseance(emp[4][3]);
                this.v16.setBackground(Color.red);
                /*Seance seance20 = new Seance(srat.getnumseance());
                srat.addRattrapage(seance20);*/
                break;
            default:
                srat = null;
                JOptionPane.showMessageDialog(this, "Selectionnez une seance!", "Emploi du temps", JOptionPane.INFORMATION_MESSAGE);
                return;    
        }
        
        if(srat.getNumSeance() == 0) {
            JOptionPane.showMessageDialog(this, "Selectionnez une seance valide!", "Emploi du temps", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        this.ae.desktop.removeAll();
        this.ae.desktop.repaint();
        this.srat.setAE(ae);
        this.srat.setMonEmp(this);
        this.ae.desktop.add(this.srat);
        
        try {
            this.srat.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AcceuilEnseignant.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.srat.show();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void initEmp(){
        
        Date dateSysteme = new Date(Calendar.getInstance().getTime().getTime());
        jDateChooser1.setDate(dateSysteme);
        dateSysteme = this.getMonday(dateSysteme);
        Date semaineFin = this.getFriday(dateSysteme);
        this.getEmp(dateSysteme, semaineFin);
    }
    
    public Date getMonday(Date d) {
        
        Calendar cal = Calendar.getInstance();
        cal.setTime(d);
        int x = cal.get(Calendar.DAY_OF_WEEK);
        switch (x) {
            case 1:
                x = 1;
                break;
            case 2: 
                x = 0;
                break;
            case 3:
                x = -1;
                break;
            case 4:
                x = -2;
                break;
            case 5:
                x = -3;
                break;
            case 6:
                x = -4;
                break;
            default:
                x = 2;
                break;        
        }
        
        cal.add(Calendar.DATE, x);
        return new Date(cal.getTimeInMillis());
    }
    
    
    public Date getFriday(Date d) {
        Calendar cal = Calendar.getInstance();
        cal.setTime(d);
        cal.add(Calendar.DATE, 4);
        return new Date(cal.getTimeInMillis());
    }
    
    
    private String idUser;
    private int numEns;
    
    public void setIDUserMEE(String s){
        this.idUser = s;
        EnseignantDAO ed = new EnseignantDAO(ConnexionBD.init());
        Enseignant ens = ed.findByIDUser(this.idUser);
        this.numEns = ens.getNumEns();
        
    }
    
    int[][] emp = new int[5][4];
    public void resetEMP() {
        l8text.setText(null);
            jLabel32.setText(null);

            jLabel13.setText(null);
            jLabel33.setText(null);

            jLabel14.setText(null);
            jLabel34.setText(null);

            jLabel15.setText(null);
            jLabel35.setText(null);

            jLabel16.setText(null);
            jLabel36.setText(null);

            jLabel17.setText(null);
            jLabel37.setText(null);

            jLabel18.setText(null);
            jLabel38.setText(null);

            jLabel19.setText(null);
            jLabel39.setText(null);

            jLabel20.setText(null);
            jLabel40.setText(null);

            jLabel21.setText(null);
            jLabel41.setText(null);

            jLabel22.setText(null);
            jLabel42.setText(null);

            jLabel23.setText(null);
            jLabel43.setText(null);

            jLabel24.setText(null);
            jLabel44.setText(null);

            jLabel25.setText(null);
            jLabel45.setText(null);

            jLabel26.setText(null);
            jLabel46.setText(null);

            jLabel27.setText(null);
            jLabel47.setText(null);

            jLabel26.setText(null);
            jLabel46.setText(null);

            jLabel27.setText(null);
            jLabel47.setText(null);

            jLabel28.setText(null);
            jLabel48.setText(null);

            jLabel29.setText(null);
            jLabel49.setText(null);
 
    }
    
    public void getEmp(Date dd, Date df){
        this.resetEMP();
        ConsulterEMP ce = new ConsulterEMP();
        ArrayList listGrpMat = ce.getGrpMat(this.numEns, dd, df);
        String[] strings;
        for (int i = 0; i < listGrpMat.size(); i++) {
            strings = (String[]) listGrpMat.get(i);
            if(strings[3] != null) {
                if(strings[3].equals("2")) {

                    if(strings[4].equals("08:00:00")) {
                        System.out.println("Hey I'm here");
                        emp[0][0] = Integer.valueOf(strings[6]);
                        l8text.setText(strings[0]);
                        jLabel32.setText(strings[1] + " " + strings[2]);
                        l8.updateUI();
                    }
                   
                    else if(strings[4].equals("10:00:00")) {
                        emp[0][1] = Integer.valueOf(strings[6]);
                        jLabel13.setText(strings[0]);
                        jLabel33.setText(strings[1] + " " + strings[2]);
                        l10.updateUI();
                    }
                    else if(strings[4].equals("14:00:00")) {
                        emp[0][2] = Integer.valueOf(strings[6]);
                        jLabel14.setText(strings[0]);
                        jLabel34.setText(strings[1] + " " + strings[2]);
                        l14.updateUI();
                    }
                    else {
                        emp[0][3] = Integer.valueOf(strings[6]);
                        jLabel15.setText(strings[0]);
                        jLabel35.setText(strings[1] + " " + strings[2]);
                        l16.updateUI();
                    }
                }

                else if(strings[3].equals("3")) {
                    if(strings[4].equals("08:00:00")) {
                        emp[1][0] = Integer.valueOf(strings[6]);
                        jLabel16.setText(strings[0]);
                        jLabel36.setText(strings[1] + " " + strings[2]);
                        ma8.updateUI();
                    }

                    else if(strings[4].equals("10:00:00")) {
                        emp[1][1] = Integer.valueOf(strings[6]);
                        jLabel17.setText(strings[0]);
                        jLabel37.setText(strings[1] + " " + strings[2]);
                        ma10.updateUI();
                    }
                    else if(strings[4].equals("14:00:00")) {
                        emp[1][2] = Integer.valueOf(strings[6]);
                        jLabel18.setText(strings[0]);
                        jLabel38.setText(strings[1] + " " + strings[2]);
                        ma14.updateUI();
                    }
                    else {
                        emp[1][3] = Integer.valueOf(strings[6]);
                        jLabel19.setText(strings[0]);
                        jLabel39.setText(strings[1] + " " + strings[2]);
                    }
                }

                else if(strings[3].equals("4")) {
                    if(strings[4].equals("08:00:00")) {
                        emp[2][0] = Integer.valueOf(strings[6]);
                        jLabel20.setText(strings[0]);
                        jLabel40.setText(strings[1] + " " + strings[2]);
                    }

                    else if(strings[4].equals("10:00:00")) {
                        emp[2][1] = Integer.valueOf(strings[6]);
                        jLabel21.setText(strings[0]);
                        jLabel41.setText(strings[1] + " " + strings[2]);
                    }
                    else if(strings[4].equals("14:00:00")) {
                        emp[2][2] = Integer.valueOf(strings[6]);
                        jLabel22.setText(strings[0]);
                        jLabel42.setText(strings[1] + " " + strings[2]);
                    }
                    else {
                        emp[2][3] = Integer.valueOf(strings[6]);
                        jLabel23.setText(strings[0]);
                        jLabel43.setText(strings[1] + " " + strings[2]);
                    }
                }

                else if(strings[3].equals("5")) {
                    if(strings[4].equals("08:00:00")) {
                        emp[3][0] = Integer.valueOf(strings[6]);
                        jLabel24.setText(strings[0]);
                        jLabel44.setText(strings[1] + " " + strings[2]);
                    }

                    else if(strings[4].equals("10:00:00")) {
                        emp[3][1] = Integer.valueOf(strings[6]);
                        jLabel25.setText(strings[0]);
                        jLabel45.setText(strings[1] + " " + strings[2]);
                    }
                    else if(strings[4].equals("14:00:00")) {
                        emp[3][2] = Integer.valueOf(strings[6]);
                        jLabel26.setText(strings[0]);
                        jLabel46.setText(strings[1] + " " + strings[2]);
                        j14.updateUI();
                    }
                    else {
                        emp[3][3] = Integer.valueOf(strings[6]);
                        jLabel27.setText(strings[0]);
                        jLabel47.setText(strings[1] + " " + strings[2]);
                    }
                }

                else if (strings[3].equals("6")) {
                    if(strings[4].equals("08:00:00")) {
                        emp[4][0] = Integer.valueOf(strings[6]);
                        jLabel26.setText(strings[0]);
                        jLabel46.setText(strings[1] + " " + strings[2]);
                    }

                    else if(strings[4].equals("10:00:00")) {
                        emp[4][1] = Integer.valueOf(strings[6]);
                        jLabel27.setText(strings[0]);
                        jLabel47.setText(strings[1] + " " + strings[2]);
                    }
                    else if(strings[4].equals("14:00:00")) {
                        emp[4][2] = Integer.valueOf(strings[6]);
                        jLabel28.setText(strings[0]);
                        jLabel48.setText(strings[1] + " " + strings[2]);
                    }
                    else {
                        emp[4][3] = Integer.valueOf(strings[6]);
                        jLabel29.setText(strings[0]);
                        jLabel49.setText(strings[1] + " " + strings[2]);
                    }
                }

                else {
                   
                }
            
            }
            
            else {
                
            }
            
            this.updateUI();
        }
        
        if(listGrpMat.size() == 0) {
              this.resetEMP();
        }
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consulter;
    private javax.swing.JPanel j10;
    private javax.swing.JPanel j14;
    private javax.swing.JPanel j16;
    private javax.swing.JPanel j8;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel l10;
    private javax.swing.JPanel l14;
    private javax.swing.JPanel l16;
    private javax.swing.JPanel l8;
    private javax.swing.JLabel l8text;
    private javax.swing.JPanel ma10;
    private javax.swing.JPanel ma14;
    private javax.swing.JPanel ma16;
    private javax.swing.JPanel ma8;
    private javax.swing.JPanel me10;
    private javax.swing.JPanel me14;
    private javax.swing.JPanel me16;
    private javax.swing.JPanel me8;
    private javax.swing.JPanel v10;
    private javax.swing.JPanel v14;
    private javax.swing.JPanel v16;
    private javax.swing.JPanel v8;
    // End of variables declaration//GEN-END:variables
}
