/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.planning.view.Enseignant;

import com.planning.controler.Absenter;
import com.planning.controler.Permut;
import com.planning.dao.implement.CreneauDAO;
import com.planning.dao.implement.SeanceDAO;
import com.planning.model.ConnexionBD;
import com.planning.model.Creneau;
import com.planning.model.Enseignant;
import com.planning.model.Seance;
import java.sql.Connection;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Azough Mehdi
 */
public class SeanceRattrapage extends javax.swing.JInternalFrame {

    /**
     * Creates new form SeanceRattrapage
     */
    private int numseance;
    Connection con=ConnexionBD.init();
    
    public void setnumseance(int i){
        this.numseance = i;
        SeanceDAO seanceDAO = new SeanceDAO(con);
        Seance seance = seanceDAO.find(this.numseance);
        //this.getRattrapage(seance);
        this.addRattrapage(seance);
    }
    
    public int getnumseance(){
        int num = this.numseance;
        return num;
    }
    
    public static String getDateName(Date d){
        
        Calendar cal = Calendar.getInstance();
        cal.setTime(d);
        int day = cal.get(Calendar.DAY_OF_WEEK);
        //System.out.print("Today  is");
        switch (day) {
            case 1:
                return "Dimanche";
            case 2:
                return "Lundi";
            case 3:
                return "Mardi";
            case 4:
                return "Mercredi";
            case 5:
                return "Jeudi";
            case 6:
                return "Vendredi";
            default:
                return "Samedi";
        }
    }
    
    public void addRattrapage(Seance seance){
        CreneauDAO creneauDAO = new CreneauDAO(con);
        Creneau obj;
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
        Absenter absenter = new Absenter(seance);
        ArrayList creno = absenter.getCreneauxMatchEnsGroupe();
        if(creno != null) {
            Object rowDataabs[] = new Object[5];
            for(int i = 0; i < creno.size(); i++) {
                obj = creneauDAO.find((int) creno.get(i));
                rowDataabs[0] = obj.getNumCreneau();
                rowDataabs[1] = getDateName(obj.getDateCreneau());
                rowDataabs[2] = obj.getDateCreneau();
                rowDataabs[3] = obj.getHeureCreneau();
                rowDataabs[4] = null;
                model.addRow(rowDataabs);
            }   
        }else JOptionPane.showMessageDialog(null, "Aucun creno vide trouvée.");
        
        ArrayList permut = absenter.getPermutPossible();
        if(permut != null) {
            Permut x;
            for(int j = 0; j < permut.size(); j++) {
            x = (Permut) permut.get(j);
                int numEnsX = x.getNumEns();
                Enseignant enseignant = new Enseignant(numEnsX);
                Object rowDataper[] = new Object[5];
                ArrayList listCreneauEnsX = x.getCreneaux();
                for(int k = 0; k < listCreneauEnsX.size(); k++){
                    obj = creneauDAO.find((int) listCreneauEnsX.get(k));
                    rowDataper[0] = obj.getNumCreneau();
                    rowDataper[1] = getDateName(obj.getDateCreneau());
                    rowDataper[2] = obj.getDateCreneau();
                    rowDataper[3] = obj.getHeureCreneau();
                    rowDataper[4] = enseignant.getNomEns();
                    model.addRow(rowDataper);
                }

            }
        
        }
    }
    
    
    public SeanceRattrapage(){
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        table = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("seances rattrapage");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Matière");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        jLabel4.setText("Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel5.setText("Heure");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 210, 120));

        jButton1.setText("Confirmer");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 140, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Veuillez selectionner un créneau convenable :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Séance à reporté ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NumCreneau", "Jour", "DateCreneau", "HeureCreneau", "Professeur"
            }
        ));
        table.setViewportView(jTable2);

        scrollPane1.add(table);

        getContentPane().add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 450, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable2;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JScrollPane table;
    // End of variables declaration//GEN-END:variables
}
