/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.planning.view.AdminSyst;

import com.planning.dao.implement.EnseignantDAO;
import com.planning.dao.implement.FiliereDAO;
import com.planning.dao.implement.UsersDAO;
import com.planning.model.ConnexionBD;
import com.planning.model.Enseignant;
import com.planning.model.Filiere;
import com.planning.model.Users;
import java.awt.Color;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Azough Mehdi
 */
public class Ajouter_Modifier_Util extends javax.swing.JFrame {
    
    /**
     * Creates new form Ajouter_Modifier_Util
     */
    private GererUtilisateurs gererUtil;
    private FiliereDAO filD;
    private ArrayList listefil;
    private Filiere fil;
    private Connection conn = ConnexionBD.init();
    
    public void getGererUtili(GererUtilisateurs gu){
        this.gererUtil = gu;
    }
    public Ajouter_Modifier_Util() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prenomfield = new javax.swing.JTextField();
        mailfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        telfield = new javax.swing.JTextField();
        idfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Enregistrer = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fonctionCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        filiereCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomfieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 250, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nom *");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Prenom *");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        prenomfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomfieldActionPerformed(evt);
            }
        });
        getContentPane().add(prenomfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 250, 30));
        getContentPane().add(mailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 250, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("mail *");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Tel *");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        getContentPane().add(telfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 250, 30));

        idfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfieldActionPerformed(evt);
            }
        });
        getContentPane().add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 250, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("ID *");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        Enregistrer.setText("Enregistrer");
        Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerActionPerformed(evt);
            }
        });
        getContentPane().add(Enregistrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 120, 30));

        Annuler.setText("Annuler");
        Annuler.setToolTipText("");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        getContentPane().add(Annuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 120, 30));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel1.setText("Fonction *");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        fonctionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enseignant", "Coordinateur Filiere", "Chef Departement", "Administrateur Departement", "Administrateur Systeme" }));
        fonctionCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fonctionComboItemStateChanged(evt);
            }
        });
        getContentPane().add(fonctionCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 250, 30));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel2.setText("Filière :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, 20));

        getContentPane().add(filiereCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 250, 30));

        setSize(new java.awt.Dimension(410, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void init() {
        this.getContentPane().setBackground(Color.white);
        filD = new FiliereDAO(conn);
        listefil = filD.findAll();
        for (int i = 0; i < listefil.size(); i++) {
            
            fil= (Filiere)listefil.get(i);
            filiereCombo.addItem(fil.getNomFiliere());
            
        }
        
        filiereCombo.setSelectedIndex(-1);
        fonctionCombo.setSelectedIndex(-1);
    }
    
    private void prenomfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomfieldActionPerformed

    private void idfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfieldActionPerformed

    private void nomfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomfieldActionPerformed

    private void EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerActionPerformed
        // TODO add your handling code here:
        
        UsersDAO usersDAO = new UsersDAO(ConnexionBD.init());
        EnseignantDAO enseignantDAO = new EnseignantDAO(ConnexionBD.init());
        
        String nom = nomfield.getText();
        
        String prenom = prenomfield.getText();
        String mail =mailfield.getText();
        String tels = telfield.getText();
        int findex = fonctionCombo.getSelectedIndex();
        int filindex = filiereCombo.getSelectedIndex();
        String id = idfield.getText();
        if(nom.equals("") || prenom.equals("") || id.equals("") || mail.equals("") || tels.equals("") || findex == -1) {
            JOptionPane.showMessageDialog(null, "Remplissez tous les champs obligatoires!", "Ajout d'un utilisateur", JOptionPane.INFORMATION_MESSAGE );
            return;
        }
        
        String fonction = (String) fonctionCombo.getSelectedItem();
        String filierenom = (String) filiereCombo.getSelectedItem();
        int numFiliere = 0;
        if(filindex == -1) {
            if(findex != 4) {
                String text = "Veuillez indiquer une filiere!";
                JOptionPane.showMessageDialog(null, text, "Ajout d'un utilisateur", JOptionPane.INFORMATION_MESSAGE );
                return;
            }
                
        } else {
            if(findex == 4) {
                String text = "L'utilisateur est un administrateur système. Il n'appartient donc à aucune filiere!";
                JOptionPane.showMessageDialog(null, text, "Ajout d'un utilisateur", JOptionPane.INFORMATION_MESSAGE );
                filiereCombo.setSelectedIndex(-1);
                return;
            }
            for (int i = 0; i < listefil.size(); i++) {
                fil = (Filiere) listefil.get(i);
                if(filierenom.equals(fil.getNomFiliere())) {
                    numFiliere = fil.getNumFiliere();
                    break;
                }
            }
        }
        
        
        String mdp = id +"emi";
        Long tel = Long.valueOf(tels);
        Users user = new Users(id,mdp, fonction, numFiliere);
        user.setFonction(fonction);
        Enseignant ens = new Enseignant(10,nom,prenom,mail,tel,id);      
        usersDAO.create(user);
        enseignantDAO.create(ens);
        this.gererUtil.updateTable();

        this.dispose();
    }//GEN-LAST:event_EnregistrerActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
            this.dispose();
    }//GEN-LAST:event_AnnulerActionPerformed

    private void fonctionComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fonctionComboItemStateChanged

        if(fonctionCombo.getSelectedIndex() == 4) {
            filiereCombo.setEnabled(false);
            return;
            
        }
        filiereCombo.setEnabled(true);
    }//GEN-LAST:event_fonctionComboItemStateChanged

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Ajouter_Modifier_Util.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Ajouter_Modifier_Util.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Ajouter_Modifier_Util.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Ajouter_Modifier_Util.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Ajouter_Modifier_Util().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JButton Enregistrer;
    private javax.swing.JComboBox<String> filiereCombo;
    private javax.swing.JComboBox<String> fonctionCombo;
    public javax.swing.JTextField idfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JTextField mailfield;
    public javax.swing.JTextField nomfield;
    public javax.swing.JTextField prenomfield;
    public javax.swing.JTextField telfield;
    // End of variables declaration//GEN-END:variables
}
