/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.planning.view.AdminSyst;

import com.planning.dao.implement.EnseignantDAO;
import com.planning.dao.implement.UsersDAO;
import com.planning.model.ConnexionBD;
import com.planning.model.Enseignant;
import com.planning.model.Users;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Azough Mehdi
 */
public class GererUtilisateurs extends javax.swing.JInternalFrame {
    ResultSet resultat = null;

    /**
     * Creates new form SeanceRattrapage
     */
    public GererUtilisateurs() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        UpdateTable();
    }
   /* public int getNumEns(){
        int row = listeutilisateur.getSelectedRow();
        int numEns = Integer.parseInt(listeutilisateur.getModel().getValueAt(row,0).toString());
        return numEns ;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeutilisateur = new javax.swing.JTable();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        Ajouter = new javax.swing.JButton();

        setTitle("utilisateurs");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gestion Utilisateurs");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        listeutilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Azough", "Mehdi", "sqdqsd", "qsdsqd", "sqdqsdqs"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nom", "Prenom", "Mail", "Tel", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listeutilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeutilisateurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeutilisateur);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 740, 380));

        modifier.setText("Modifier");
        modifier.setEnabled(false);
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        getContentPane().add(modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 130, 30));

        supprimer.setText("Supprimer");
        supprimer.setEnabled(false);
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supprimer(evt);
            }
        });
        getContentPane().add(supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 130, 30));

        Ajouter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ajouter.setText("Ajouter");
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterActionPerformed(evt);
            }
        });
        getContentPane().add(Ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        listeutilisateur.clearSelection();
        modifier.setEnabled(false);
        supprimer.setEnabled(false);
    }//GEN-LAST:event_formMouseClicked

    private void listeutilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeutilisateurMouseClicked
        modifier.setEnabled(true);
        supprimer.setEnabled(true);
    }//GEN-LAST:event_listeutilisateurMouseClicked

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        int row = listeutilisateur.getSelectedRow();
        //int numEns = Integer.parseInt(listeutilisateur.getModel().getValueAt(row,0).toString());
        
        String nom =listeutilisateur.getModel().getValueAt(row,1).toString();
        String prenom =listeutilisateur.getModel().getValueAt(row,2).toString();
        String mail =listeutilisateur.getModel().getValueAt(row,3).toString();
        String tel =listeutilisateur.getModel().getValueAt(row,4).toString();
        String id =listeutilisateur.getModel().getValueAt(row,5).toString();

        Modifier_Util modifier = new Modifier_Util();
        modifier.setTitle("Modifier");
        modifier.nomfield.setText(nom);
        modifier.prenomfield.setText(prenom);
        modifier.mailfield.setText(mail);
        modifier.telfield.setText(tel);
        modifier.idfield.setText(id);
        modifier.setVisible(true);
        //modifier.getGererUtili(this);
    }//GEN-LAST:event_modifierActionPerformed

    private void AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterActionPerformed
        Ajouter_Util ajouter = new Ajouter_Util();
        ajouter.setTitle("Ajouter");
        ajouter.getGererUtili(this);
        ajouter.setVisible(true);
    }//GEN-LAST:event_AjouterActionPerformed

    private void Supprimer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supprimer
        // TODO add your handling code here:
        UsersDAO usersDAO = new UsersDAO(ConnexionBD.init());
        EnseignantDAO enseignantDAO = new EnseignantDAO(ConnexionBD.init());
        
        int row = listeutilisateur.getSelectedRow();
        int numeroEns = Integer.parseInt(listeutilisateur.getModel().getValueAt(row,0).toString());
        String nom =listeutilisateur.getModel().getValueAt(row,1).toString();
        String prenom =listeutilisateur.getModel().getValueAt(row,2).toString();
        String mail =listeutilisateur.getModel().getValueAt(row,3).toString();
        String tel =listeutilisateur.getModel().getValueAt(row,4).toString() ;
        String id =listeutilisateur.getModel().getValueAt(row,5).toString();
        
        
        Enseignant ens = new Enseignant(numeroEns, nom, prenom, mail, tel, id);
        Users user = new Users(id);
        Enseignant enseignant = enseignantDAO.findByIDUser(id);
        //System.out.println(enseignant.getNumEns());
        usersDAO.delete(user);
        enseignantDAO.delete(ens);
        
        JOptionPane.showMessageDialog(null, "Enseignant supprimé avec succès");
        
        UpdateTable();
    }//GEN-LAST:event_Supprimer
  
    public void UpdateTable(){
           EnseignantDAO enseignantDAO = new EnseignantDAO(ConnexionBD.init());
           resultat = enseignantDAO.getAllEnseignant();
           listeutilisateur.setModel(DbUtils.resultSetToTableModel(resultat)); 
    }
    
    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        UsersDAO usersDAO = new UsersDAO(ConnexionBD.init());
        EnseignantDAO enseignantDAO = new EnseignantDAO(ConnexionBD.init());
        
        int row = listeutilisateur.getSelectedRow();
        int numeroEns = Integer.parseInt(listeutilisateur.getModel().getValueAt(row,0).toString());
        String nom =listeutilisateur.getModel().getValueAt(row,1).toString();
        String prenom =listeutilisateur.getModel().getValueAt(row,2).toString();
        String mail =listeutilisateur.getModel().getValueAt(row,3).toString();
        String tel =listeutilisateur.getModel().getValueAt(row,4).toString() ;
        String id =listeutilisateur.getModel().getValueAt(row,5).toString();
        
        
        Enseignant ens = new Enseignant(numeroEns, nom, prenom, mail, tel, id);
        Users user = new Users(id);
        Enseignant enseignant = enseignantDAO.findByIDUser(id);
        //System.out.println(enseignant.getNumEns());
        usersDAO.delete(user);
        enseignantDAO.delete(ens);
        
        JOptionPane.showMessageDialog(null, "Enseignant supprimé avec succès");
        
        UpdateTable();
        
    }                                         


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable listeutilisateur;
    private javax.swing.JButton modifier;
    private javax.swing.JButton supprimer;
    // End of variables declaration//GEN-END:variables
}
