/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.planning.view.AdminSyst;

import com.planning.view.Enseignant.*;
import com.planning.view.AdminSyst.*;
import com.planning.dao.implement.EnseignantDAO;
import com.planning.dao.implement.UsersDAO;
import com.planning.model.ConnexionBD;
import com.planning.model.Enseignant;
import com.planning.model.Users;
import javax.swing.JOptionPane;

/**
 *
 * @author Azough Mehdi
 */
public class Modifier2 extends javax.swing.JFrame {
    
    /**
     * Creates new form Ajouter_Modifier_Util
     */
    private MonCompteSyst monCompteSys;
    private AcceuilEnseignant ae;
    String iduser;
    
    public void setGererUtili(MonCompteSyst mcs){
        this.monCompteSys = mcs;
    }
    
    
    public void setIDUserMod2(String id){
        this.iduser = id;
        System.out.println(this.iduser);
        idfield.setText(this.iduser);
        
        EnseignantDAO enseignantDAO = new EnseignantDAO(ConnexionBD.init());
        Enseignant ens = enseignantDAO.findByIDUser(idfield.getText());
        
        nomfield.setText(ens.getNomEns());
        prenomfield.setText(ens.getPrenomEns());
        mailfield.setText(ens.getMail());
        telfield.setText(String.valueOf(ens.getTel()));
    }
    
    public Modifier2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prenomfield = new javax.swing.JTextField();
        mailfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        telfield = new javax.swing.JTextField();
        idfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Enregistrer = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomfieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 250, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nom");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Prenom");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        prenomfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomfieldActionPerformed(evt);
            }
        });
        getContentPane().add(prenomfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 250, 30));
        getContentPane().add(mailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 250, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("mail");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Tel");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        getContentPane().add(telfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 250, 30));

        idfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfieldActionPerformed(evt);
            }
        });
        getContentPane().add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 250, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        Enregistrer.setText("Enregistrer");
        Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerActionPerformed(evt);
            }
        });
        getContentPane().add(Enregistrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 120, 30));

        Annuler.setText("Annuler");
        Annuler.setToolTipText("");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        getContentPane().add(Annuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 120, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prenomfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomfieldActionPerformed

    private void idfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfieldActionPerformed

    private void nomfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomfieldActionPerformed

    
    private void EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerActionPerformed
        // TODO add your handling code here:
        String nom = nomfield.getText();
        String prenom = prenomfield.getText();
        String mail = mailfield.getText();
        String tel = telfield.getText();
        String id = idfield.getText();
        
        if(nom.equals("") || prenom.equals("") || tel.equals("") || id.equals("")) {
            JOptionPane.showMessageDialog(null, "Remplissez les champs vides!", "Modification de profil", JOptionPane.INFORMATION_MESSAGE);
            return;
        } 
        
//        int p = JOptionPane.showConfirmDialog(null,"Etes-vous sur des modifications apportée?","Modification de profil", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
//        
//        if (p == JOptionPane.YES_OPTION){
            String mdp = id + "emi";
            UsersDAO usersDAO = new UsersDAO(ConnexionBD.init());
            EnseignantDAO enseignantDAO = new EnseignantDAO(ConnexionBD.init());
            Enseignant ens = enseignantDAO.findByIDUser(this.iduser);    
            ens.setNomEns(nom);
            ens.setPrenomEns(prenom);
            ens.setMail(mail);
            ens.setTel(Long.valueOf(tel));
            enseignantDAO.update(ens);
            Users user = usersDAO.find(this.iduser);
            usersDAO.update(user, new Users(id, mdp, user.getFonction(), user.getNumFiliere()));
            
//            JOptionPane.showMessageDialog(null,"Enseignant modifié avec succès");
            this.monCompteSys.setAdminSys(ens);
            this.dispose();
            
//        } else if(p == JOptionPane.NO_OPTION) this.dispose();
        
//        else {
//            
//        }
    }//GEN-LAST:event_EnregistrerActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
            dispose();
            MonCompteEnseignant mce = new MonCompteEnseignant();
            mce.setVisible(true);
    }//GEN-LAST:event_AnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifier2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifier2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifier2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifier2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modifier2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JButton Enregistrer;
    public javax.swing.JTextField idfield;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JTextField mailfield;
    public javax.swing.JTextField nomfield;
    public javax.swing.JTextField prenomfield;
    public javax.swing.JTextField telfield;
    // End of variables declaration//GEN-END:variables
}
